[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "create_rootfs"
author = "Michael Seifert"
author-email = "m.seifert@digitalernachschub.de"
home-page = "https://dev.digitalernachschub.de"
